# Generated by Django 2.1.5 on 2023-01-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_tool', '0002_auto_20230104_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
