# Generated by Django 2.1.5 on 2023-01-11 17:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('educational_tool', '0004_auto_20230107_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
                ('difficulty', models.CharField(max_length=128, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.Category')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=128, unique=True)),
                ('published', models.DateField(default=datetime.date(2023, 1, 11))),
                ('upload_file', models.FileField(max_length=254, upload_to='C:\\Users\\biere\\OneDrive - University of Glasgow\\Documents\\y3 v2\\year 4\\individual project\\Dissertation_Project\\project\\individual_project\\media')),
                ('is_private_project', models.BooleanField(default=False)),
                ('project_summary', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='tutorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=1000, unique=True)),
                ('expected_ouput', models.CharField(max_length=128, unique=True)),
                ('question', models.CharField(max_length=128, unique=True)),
                ('correct_answer', models.CharField(max_length=128, unique=True)),
                ('user_answer', models.CharField(max_length=128, unique=True)),
                ('coding_answer', models.CharField(max_length=128, unique=True)),
                ('user_coding_answer', models.CharField(max_length=128, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.Category')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='C:\\Users\\biere\\OneDrive - University of Glasgow\\Documents\\y3 v2\\year 4\\individual project\\Dissertation_Project\\project\\individual_project\\media')),
                ('author', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=128, unique=True)),
                ('url', models.CharField(max_length=5000, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='C:\\Users\\biere\\OneDrive - University of Glasgow\\Documents\\y3 v2\\year 4\\individual project\\Dissertation_Project\\project\\individual_project\\media')),
                ('UserProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.UserProfile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.Category')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.UserProfile'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educational_tool.Category'),
        ),
    ]
