# Generated by Django 2.1.5 on 2023-01-11 23:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_tool', '0005_auto_20230111_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateField(verbose_name=datetime.date(2023, 1, 11)),
        ),
    ]
