# Generated by Django 2.1.5 on 2023-02-07 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_tool', '0006_auto_20230111_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='published',
            field=models.DateField(verbose_name=datetime.date(2023, 2, 7)),
        ),
    ]
