# Generated by Django 2.1.5 on 2023-02-10 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_tool', '0008_auto_20230210_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='upload_file',
            field=models.FileField(max_length=1400, upload_to='C:\\Users\\biere\\OneDrive - University of Glasgow\\Documents\\y3 v2\\year 4\\individual project\\Dissertation_Project\\project\\individual_project\\media'),
        ),
    ]
